name: Create an Ad-Hoc Meeting
title: "[Ad hoc meeting] "
assignees:
  - bensternthal
labels:
  - cross-project-council-agenda
body:
  - type: markdown
    attributes:
      value: |
        ### Agenda for the Meeting
  - type: input
    id: facilitator
    attributes:
      label: Facilitator
      description: Who is the facilitator of this meeting?
    validations:
      required: true
  - type: input
    id: related-issues
    attributes:
      label: Related Issue(s)
      description: What are the related Issues to this Meeting?
    validations:
      required: false
  - type: input
    id: meeting-date
    attributes:
      label: Meeting Date
      description: 'When should the meeting happen? Use a MM/DD/YYY hh:mm TZ format (e.g.: 01/01/2001 00:00 UTC-3)'
    validations:
      required: true
  - type: input
    id: zoom-link
    attributes:
      label: Zoom/G Meet Libk
      description: Where should the meet happen?
      value: 'https://zoom.us/j/91398697172?pwd=QVgxRUFXdmtHVUNiODhoSU11ejF0QT09'
    validations:
      required: true
  - type: input
    id: meeting-notes
    attributes:
      label: Meeting Notes G Doc
      description: Provide a Google Doc link for the Meeting Notes
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Please wait for your meeting to be added to the [OpenJS Foundation calendar](https://calendar.openjsf.org) before using the Zoom meeting. If there are two conflicting meetings, please note that the meeting on the calendar takes precedence.

