name: 'Create an ad-hoc meeting'
description: 'This issue template is used for creating a new ad-hoc meeting for the Cross Project Council'
title: "[Ad hoc meeting] "
assignees:
  - bensternthal
labels:
  - cross-project-council-agenda
body:
  - type: markdown
    attributes:
      value: |
        ### Agenda for the Meeting
  - type: input
    id: facilitator
    attributes:
      label: Facilitator
      description: Who is the facilitator of this meeting?
    validations:
      required: true
  - type: input
    id: related-issues
    attributes:
      label: Related issue(s)
      description: What are the related issues to this meeting?
    validations:
      required: false
  - type: input
    id: meeting-date
    attributes:
      label: Date and time
      description: 'When should the meeting happen? Use a "YYYY-MM-DD HH:MM TZ" format (e.g.: 2009-05-27 13:00 GMT+1)'
    validations:
      required: true
  - type: input
    id: zoom-link
    attributes:
      label: Zoom link
      description: Where should the meeting happen?
      value: 'https://zoom.us/j/91398697172?pwd=QVgxRUFXdmtHVUNiODhoSU11ejF0QT09'
    validations:
      required: true
  - type: input
    id: meeting-notes
    attributes:
      label: URL for meeting notes
      description: Provide link to Agenda
  - type: markdown
    attributes:
      value: |
        Please wait for your meeting to be added to the [OpenJS Foundation calendar](https://calendar.openjsf.org) before using the Zoom meeting. If there are two conflicting meetings, please note that the meeting on the calendar takes precedence.

