name: Generic Issue
description: Open a generic Issue for the OpenJS CPC
labels:
  - cross-project-council-agenda
body:
  - type: markdown
    attributes:
      value: |
        ### OpenJS Cross Project Council

        Thank you for opening an issue for the OpenJS Cross Project Council.

        **Please remember to follow the Code of Conduct and be respectful.**
  - type: input
    id: topic
    attributes:
      label: What is this Issue about?
      description: How can the CPC help you out?
    validations:
      required: false
  - type: textarea
    id: details
    attributes:
      label: Request Details
      description: Provide us more details about your request to the CPC
    validations:
      required: true
  - type: dropdown
    id: type
    attributes:
      label: Request Type
      description: What is this Issue about?
      options:
        - General Question
        - Resource Request
        - CPC Agenda
        - Legal Request
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/openjs-foundation/cross-project-council/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow the OpenJS Foundation Code of Conduct
          required: true
