name: Generic Issue
description: Open a generic Issue for the OpenJS CPC
body:
  - type: markdown
    attributes:
      value: |
        ### OpenJS Cross Project Council

        Thank you for opening an issue for the OpenJS Cross Project Council.

        **Please remember to give a read to our [Code of Conduct](https://github.com/openjs-foundation/cross-project-council/blob/main/CODE_OF_CONDUCT.md) if you're a newcomer.**
  - type: input
    id: topic
    attributes:
      label: What is this Issue about?
      description: How can the CPC help you out?
    validations:
      required: false
  - type: textarea
    id: details
    attributes:
      label: Request Details
      description: Provide us more details about your request to the CPC
    validations:
      required: true
  - type: dropdown
    id: type
    attributes:
      label: Request Type
      description: What is this Issue about?
      options:
        - General Discussion that requires the CPC attention
        - Request for supporting a new Resource (e.g. GitHub Feature)
        - Topic for the CPC Agenda/Working Sessions
        - Repository Bug Report (e.g. broken link)
    validations:
      required: true
